name: ipa-system
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  pgadmin:
    extends:
      file: ./pgadmin.yml
      service: pgadmin
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
  redis:
    extends:
      file: ./redis.yml
      service: redis

networks:
  shared_network:
    external: true
